from random import choice

wechat_emoji = [
    '[裂开]', '[苦涩]', '[叹气]', '[让我看看]', '[666]', '/尴尬', '/酷', '/奋斗', '/疑问',
    '/擦汗', '/抠鼻', '/鄙视', '/勾引', '/差劲', '[NO]', '/跳跳', '/转圈', '/回头', '/激动',
    '/左太极', '/右太极', '[福]', '[奸笑]', '[嘿哈]', '[捂脸]', '[机智]', '[加油]', '[加油加油]',
    '[社会社会]', '[吃瓜]', '[翻白眼]', '/微笑', '/撇嘴', '/色', '/发呆', '/得意', '/流泪',
    '/害羞', '/闭嘴', '/睡', '/大哭', '/发怒', '/调皮', '/呲牙', '/惊讶', '/难过', '/冷汗',
    '/抓狂', '/吐', '/偷笑', '/可爱', '/白眼', '/傲慢', '/饥饿', '/困', '/惊恐', '/流汗',
    '/憨笑', '[悠闲]', '/咒骂', '/嘘', '/晕', '/折磨', '/衰', '/骷髅', '/敲打', '/再见',
    '/鼓掌', '/糗大了', '/坏笑', '/左哼哼', '/右哼哼', '/哈欠', '/委屈', '/快哭了', '/阴险',
    '/亲亲', '/吓', '/可怜', '/菜刀', '/西瓜', '/啤酒', '/篮球', '/乒乓', '/咖啡', '/饭',
    '/猪头', '/玫瑰', '/凋谢', '/示爱', '/爱心', '/心碎', '/礼物', '/闪电', '/炸弹', '/刀',
    '/足球', '/便便', '/月亮', '/太阳', '/礼物', '/拥抱', '[强]', '[弱]', '/握手', '/胜利',
    '/抱拳', '/拳头', '/爱你', '[OK]', '/爱情', '/飞吻', '/发抖', '/怄火', '/磕头', '/挥手',
    '/街舞', '/献吻', '[發]', '[红包]', '[耶]', '[皱眉]', '[Emm]', '[好的]', '[天啊]', '[打脸]',
    '[汗]', '[蛋糕]', '[合十]', '/礼物', '[庆祝]', '[破涕为笑]', '[笑脸]', '[无语]','[失望]',
    '[恐惧]', '[脸红]', '[哇]', '[旺柴]', '/瓢虫'
]

all_emoji = {
    "Slightly smiling face": "🙂",
    "Smiling face": "😀",
    "Smiling face with big eyes": "😃",
    "Smiling face with smiling eyes": "😊",
    "Beaming face with smiling eyes": "😁",
    "Smiling face with tears": "🥲",
    "Grinning face": "😆",
    "Rolling on the floor laughing": "🤣",
    "Lauging with tears": "😂",
    "Upside down face": "🙃",
    "Winking face": "😉",
    "Smiling face with halo": "😇",
    "Smiling face with sunglasses": "😎",
    "Nerdy face": "🤓",
    "Face with monocle": "🧐",
    "Partying face": "🥳",
    "Smiling face with hearts": "🥰",
    "Smiling face with heart eyes": "😍",
    "Star-struck": "🤩",
    "Face blowing kiss": "😘",
    "Kissing face": "😗",
    "Kissing face with closed eyes": "😚",
    "Kissng face with smiling eyes": "😙",
    "Yummy face": "😋",
    "Face with tongue": "😛",
    "WInking face with tongue": "😜",
    "Zany face": "🤪",
    "Squinting face with tongue": "😝",
    "Money face with money tongue": "🤑",
    "Hugs": "🤗",
    "Face with hand in mouth": "🤭",
    "Shushing face": "🤫",
    "Thinking face": "🤔",
    "Neutral face": "😐",
    "Zipped mouth": "🤐",
    "Face with raised eyebrow": "🤨",
    "Expressionless face": "😑",
    "Face with no mouth": "😶",
    "Smirking face": "😏",
    "Unamused face": "😒",
    "Face with rolling eyes": "🙄",
    "Grimacing face": "😬",
    "Lying face": "🤥",
    "Sleepy face": "😪",
    "Sleeping face": "😴",
    "Relieved face": "😌",
    "Pensive face": "😔",
    "Drooling face": "🤤",
    "Face with mask": "😷",
    "Face with thermometer": "🤒",
    "Face with bandage": "🤕",
    "Nauseous face": "🤢",
    "Vomiting face": "🤮",
    "Sneezing face": "🤧",
    "Hot face": "🥵",
    "Cold face": "🥶",
    "Woozy face": "🥴",
    "Face with crossed-out eyes": "😵",
    "Face with exploding head": "🤯",
    "Confused face": "😕",
    "Worried face": "😟",
    "Slightly frowning face": "🙁",
    "Frowning face": "☹",
    "Face with open mouth": "😮",
    "Hushed face": "😯",
    "Astonished face": "😲",
    "Flushed face": "😳",
    "Begging face": "🥺",
    "Frowning face with open mouth": "😦",
    "Angushed face": "😧",
    "Fearful face": "😨",
    "Anxious face with sweat": "😰",
    "Sad but relieved face": "😥",
    "Crying face": "😢",
    "Loudly crying face": "😭",
    "Screaming face": "😱",
    "Confounded face": "😖",
    "Persevering face": "😣",
    "Disappointed face": "😞",
    "Downcast face with sweat": "😓",
    "Weary face": "😩",
    "Tired face": "😫",
    "Yawning face": "🥱",
    "Face with steam": "😤",
    "Pouting face": "😡",
    "Angry face": "😠",
    "Face with symbols on mouth": "🤬",
    "Smiling face with horns": "😈",
    "Angry face with horns": "👿",
    "Skull": "💀",
    "Skull and cross-bone": "☠",
    "Pile of poo": "💩",
    "Clown": "🤡",
    "Ogre": "👹",
    "Goblin": "👺",
    "Ghost": "👻",
    "Alien": "👽",
    "Alien monster": "👾",
    "Robot": "🤖",
    "Face in clouds": "😶‍🌫️",
    "Face exhaling": "😮‍💨",
    "Face with spiral eyes": "😵‍💫",
    "Heart on fire": "❤️‍🔥",
    "Mending heart": "❤️‍🩹",
    "Eye in speech bubble": "👁️‍🗨️",
    "Man with beard": "🧔‍♂️",
    "Woman with beard": "🧔‍♀️",
    "Man with red hair": "👨‍🦰",
    "Man with curly hair": "👨‍🦱",
    "Man with white hair": "👨‍🦳",
    "Man with bald head": "👨‍🦲",
    "Woman with red hair": "👩‍🦰",
    "Person with red hair": "🧑‍🦰",
    "Woman with curly hair": "👩‍🦱",
    "Person with curly hair": "🧑‍🦱",
    "Woman with white hair": "👩‍🦳",
    "Person with white hair": "🧑‍🦳",
    "Woman with bald head": "👩‍🦲",
    "Person with bald head": "🧑‍🦲",
    "Woman with blond hair": "👱‍♀️",
    "Man with blond hair": "👱‍♂️",
    "Grinnig cat": "😺",
    "Grinning cat with smiling eyes": "😸",
    "Grinning cat with tears": "😹",
    "Smiling cat with heart eyes": "😻",
    "Cat with wry smile": "😼",
    "Kissing cat": "😽",
    "Weary cat": "🙀",
    "Crying cat": "😿",
    "Pouting cat": "😾",
    "See no evil monkey": "🙈",
    "Hear no evil monkey": "🙉",
    "Speak no evil monkey": "🙊",
    "Kiss": "💏",
    "Love letter": "💌",
    "Heart with arrow": "💘",
    "Heart with ribbon": "💝",
    "Sparking heart": "💖",
    "Growing heart": "💗",
    "Beating heart": "💓",
    "Revolving heart": "💞",
    "Two hearts": "💕",
    "Heart decoration": "💟",
    "Heart exclamation": "❣",
    "Broken heart": "💔",
    "Red heart": "❤",
    "Orange heart": "🧡",
    "Yellow heart": "💛",
    "Green heart": "💚",
    "Blue heart": "💙",
    "Purple heart": "💜",
    "Brown heart": "🤎",
    "Black heart": "🖤",
    "White heart": "🤍",
    "Hundred(correct)": "💯",
    "Anger": "💢",
    "Collision": "💥",
    "Dizzy": "💫",
    "Sweat droplets": "💦",
    "Dashing away": "💨",
    "Hole": "🕳",
    "Bomb": "💣",
    "Message baloon": "💬",
    "Left speech bubble": "🗨",
    "Anger bubble": "🗯",
    "Thought baloon": "💭",
    "zzz": "💤",
    "Waving hand": "👋",
    "Raised back of hand": "🤚",
    "Hands with splayed finger": "🖐",
    "Raised hand": "✋",
    "Vulcan salute": "🖖",
    "Ok": "👌",
    "Pinched fingers": "🤌",
    "Pinched hand": "🤏",
    "Victory hand": "✌",
    "Crossed fingers": "🤞",
    "Love you": "🤟",
    "Horn sign": "🤘",
    "Call me hand": "🤙",
    "Index finger pointing left": "👈",
    "Index finger pointing right": "👉",
    "Index finger pointing up": "👆",
    "Index finger pointing down": "👇",
    "Middle finger": "🖕",
    "Forehand Index finger pointing up": "☝",
    "Index finger pointing at viewer": "🫵",
    "Thumbs up": "👍",
    "Thumbs down": "👎",
    "Raised fist": "✊",
    "Fist": "👊",
    "Left facing fist": "🤛",
    "Right facing fist": "🤜",
    "Clapping hands": "👏",
    "Raised hands": "🙌",
    "Open hands": "👐",
    "Palms together hands": "🤲",
    "Handshake": "🤝",
    "Praying hands": "🙏",
    "Writing hands": "✍",
    "Nail polish": "💅",
    "Selfie hand": "🤳",
    "Flexed biceps": "💪",
    "Mechanical arm": "🦾",
    "Leg": "🦵",
    "Mechanical leg": "🦿",
    "Foot": "🦶",
    "Ear": "👂",
    "Ear with earing aid": "🦻",
    "Nose": "👅",
    "Brain": "🧠",
    "Footprint": "👣",
    "Mechanical heart": "🫀",
    "Lungs": "🫁",
    "Tooth": "🦷",
    "Bone": "🦴",
    "Eyes": "👀",
    "Eye": "👁",
    "Mouth": "👄",
    "Person": "🧑",
    "Baby": "👶",
    "Child": "🧒",
    "Boy": "👦",
    "Girl": "👧",
    "Person with blonde hair": "👱",
    "Man": "👨",
    "Bearded person": "🧔",
    "Bearded man": "🧔‍♂‍",
    "Bearded woman": "🧔‍♀‍",
    "Bald man": "👨‍🦲",
    "Woman": "👩",
    "Bald woman": "👩‍🦲",
    "Woman with blonde hair": "👱‍♀‍",
    "Man with blonde hair": "👱‍♂‍",
    "Old person": "🧓",
    "Old man": "👴",
    "Old woman": "👵",
    "Person frowning": "🙍",
    "Man frowning": "🙍‍♂️",
    "Woman frowning": "🙍‍♀️",
    "Man pouting": "🙎‍♂️",
    "Woman pouting": "🙎‍♀️",
    "Man gesturing no": "🙅‍♂️",
    "Woman gesturing no": "🙅‍♀️",
    "Man gesturing ok": "🙆‍♂️",
    "Woman gesturing ok": "🙆‍♀️",
    "Man tipping hand": "💁‍♂️",
    "Woman tipping hand": "💁‍♀️",
    "Man raising hand": "🙋‍♂️",
    "Woman raising hand": "🙋‍♀️",
    "Deaf man": "🧏‍♂️",
    "Deaf woman": "🧏‍♀️",
    "Man bowing": "🙇‍♂️",
    "Woman bowing": "🙇‍♀️",
    "Man facepalming": "🤦‍♂️",
    "Woman facepalming": "🤦‍♀️",
    "Man shrugging": "🤷‍♂️",
    "Woman shrugging": "🤷‍♀️",
    "Health worker": "🧑‍⚕️",
    "Man health worker": "👨‍⚕️",
    "Woman health worker": "👩‍⚕️",
    "Student": "🧑‍🎓",
    "Man student": "👨‍🎓",
    "Woman student": "👩‍🎓",
    "Teacher": "🧑‍🏫",
    "Man teacher": "👨‍🏫",
    "Woman teacher": "👩‍🏫",
    "Judge": "🧑‍⚖️",
    "Woman judge": "👩‍⚖️",
    "Farmer": "🧑‍🌾",
    "Man farmer": "👨‍🌾",
    "Woman farmer": "👩‍🌾",
    "Cook": "🧑‍🍳",
    "Man cook": "👨‍🍳",
    "Woman cook": "👩‍🍳",
    "Mechanic": "🧑‍🔧",
    "Man mechanic": "👨‍🔧",
    "Woman mechanic": "👩‍🔧",
    "Factory worker": "🧑‍🏭",
    "Man factory worker": "👨‍🏭",
    "Woman factory worker": "👩‍💼",
    "Office worker": "🧑‍💼",
    "Man office worker": "👨‍💼",
    "Scientist": "🧑‍🔬",
    "Man scientist": "👨‍🔬",
    "Woman scientist": "👩‍🔬",
    "Technologist": "🧑‍💻",
    "Man technologist": "👨‍💻",
    "Woman technologist": "👩‍💻",
    "Singer": "🧑‍🎤",
    "Man singer": "👨‍🎤",
    "Woman singer": "👩‍🎤",
    "Artist": "🧑‍🎨",
    "Man artist": "👨‍🎨",
    "Woman artist": "👩‍🎨",
    "Pilot": "🧑‍✈️",
    "Man pilot": "👨‍✈️",
    "Woman pilot": "👩‍✈️",
    "Astronaut": "🧑‍🚀",
    "Man astronaut": "👨‍🚀",
    "Womanh astronaut": "👩‍🚀",
    "Firefighter": "🧑‍🚒",
    "Man firefighter": "👨‍🚒",
    "Woman firefighter": "👩‍🚒",
    "Man police": "👮‍♂️",
    "Woman police": "👮‍♀️",
    "Man detective": "🕵️‍♂️",
    "Woman detective": "🕵️‍♀️",
    "Man guard": "💂‍♂️",
    "Woman guard": "💂‍♀️",
    "Man construction worker": "👷‍♂️",
    "Woman construction worker": "👷‍♀️",
    "Man wearing turban": "👳‍♂️",
    "Woman wearing turban": "👳‍♀️",
    "Man in tuxedo": "🤵‍♂️",
    "Woman in tuxedo": "🤵‍♀️",
    "Man with veil": "👰‍♂️",
    "Woman with veil": "👰‍♀️",
    "Person feeding baby": "🧑‍🍼",
    "Woman feeding baby": "👩‍🍼",
    "Man feeding baby": "👨‍🍼",
    "Mx claus": "🧑‍🎄",
    "Man superhero": "🦸‍♂️",
    "Woman superhero": "🦸‍♀️",
    "Man supervillain": "🦹‍♂️",
    "Woman supervillain": "🦹‍♀️",
    "Man mage": "🧙‍♂️",
    "Woman mage": "🧙‍♀️",
    "Man fairy": "🧚‍♂️",
    "Woman fairy": "🧚‍♀️",
    "Man vampire": "🧛‍♂️",
    "Woman vampire": "🧛‍♀️",
    "Merman": "🧜‍♂️",
    "Mermaid": "🧜‍♀️",
    "Man elf": "🧝‍♂️",
    "Woman elf": "🧝‍♀️",
    "Man genie": "🧞‍♂️",
    "Woman genie": "🧞‍♀️",
    "Man zombie": "🧟‍♂️",
    "Woman zombie": "🧟‍♀️",
    "Man getting massage": "💆‍♂️",
    "Woman getting massage": "💆‍♀️",
    "Man getting haircut": "💇‍♂️",
    "Woman getting haircut": "💇‍♀️",
    "Man walking": "🚶‍♂️",
    "Woman walking": "🚶‍♀️",
    "Man standing": "🧍‍♂️",
    "Woman standing": "🧍‍♀️",
    "Man kneeling": "🧎‍♂️",
    "Woman kneeling": "🧎‍♀️",
    "Person with white cane": "🧑‍🦯",
    "Man with white cane": "👨‍🦯",
    "Woman with white cane": "👩‍🦯",
    "Person with motorized wheelchair": "🧑‍🦼",
    "Man in motorized wheelchair": "👨‍🦼",
    "Woman in motorized wheelchair": "👩‍🦼",
    "Person in manual wheelchair": "🧑‍🦽",
    "Man in manual wheelchair": "👨‍🦽",
    "Woman in manual wheelchair": "👩‍🦽",
    "Man running": "🏃‍♂️",
    "Woman running": "🏃‍♀️",
    "Men with bunny ears": "👯‍♂️",
    "Women with bunny ears": "👯‍♀️",
    "Man in steamy room": "🧖‍♂️",
    "Woman in steamy room": "🧖‍♀️",
    "Man climbing": "🧗‍♂‍",
    "Woman climbing": "🧗‍♀‍",
    "Man golfing": "🏌️‍♂️",
    "Woman golfing": "🏌️‍♀️",
    "Person climbing": "🧗",
    "Person fencing": "🤺",
    "Horse racing": "🏇",
    "Skier": "⛷",
    "Snowboarder": "🏂",
    "Person playing golf": "🏌",
    "Man playing golf": "🏌️‍♂‍",
    "Woman playing golf": "🏌️‍♀‍",
    "Person surfing": "🏄",
    "Man sufing": "🏄‍♂️",
    "Woman surfing": "🏄‍♀️",
    "Person rowing boat": "🚣",
    "Man rowing boat": "🚣‍♂️",
    "Woman rowing boat": "🚣‍♀️",
    "Person swimming": "🏊",
    "Man swimming": "🏊‍♂️",
    "Woman swimming": "🏊‍♀️",
    "Person bouncing ball": "⛹",
    "Man bouncing ball": "⛹️‍♂️",
    "Woman bouncing ball": "⛹️‍♀️",
    "Person lifting weight": "🏋",
    "Man lifting weights": "🏋️‍♂️",
    "Woman lifting weights": "🏋️‍♀️",
    "Person cycling": "🚴",
    "Man cycling": "🚴‍♂️",
    "Woman cycling": "🚴‍♀️",
    "Person mountain biking": "🚵",
    "Man mountain biking": "🚵‍♂️",
    "Woman mountain biking": "🚵‍♀️",
    "Person cartwheeling": "🤸",
    "Man cartwheeling": "🤸‍♂️",
    "Woman cartwheeling": "🤸‍♀️",
    "People wrestling": "🤼",
    "Men wrestling": "🤼‍♂️",
    "Women wrestling": "🤼‍♀️",
    "Person playing water polo": "🤽",
    "Man playing water polo": "🤽‍♂️",
    "Woman playing water polo": "🤽‍♀️",
    "Person playing handball": "🤾",
    "Man playing handball": "🤾‍♂️",
    "Woman playing handblall": "🤾‍♀️",
    "Person juggling": "🤹",
    "Man juggling": "🤹‍♂️",
    "Woman juggling": "🤹‍♀️",
    "Person lotus position": "🧘",
    "Man in lotus position": "🧘‍♂️",
    "Woman in lotus position": "🧘‍♀️",
    "Person bathing": "🛀",
    "Person in bed": "🛌",
    "Family": "👪",
    "Family of man, woman and boy": "👨‍👩‍👦",
    "Family of man, woman and girl": "👨‍👩‍👧",
    "Family of man, woman, boy, and girl": "👨‍👩‍👧‍👦",
    "Family of man, woman, boy, and boy": "👨‍👩‍👦‍👦",
    "Family of man, woman, girl, and girl": "👨‍👩‍👧‍👧",
    "Family of man, man, and boy": "👨‍👨‍👦",
    "Family of man, man, and girl": "👨‍👨‍👧",
    "Family of man, man, girl, and boy": "👨‍👨‍👧‍👦",
    "Family of man, man, boy, and boy": "👨‍👨‍👦‍👦",
    "Family of man, man, girl, and girl": "👨‍👨‍👧‍👧",
    "Family of woman, woman, and boy": "👩‍👩‍👦",
    "Family of woman, woman, and girl": "👩‍👩‍👧",
    "Family of woman, woman, girl, and boy": "👩‍👩‍👧‍👦",
    "Family of woman, woman, boy, and boy": "👩‍👩‍👦‍👦",
    "Family of woman, woman, girl, and girl": "👩‍👩‍👧‍👧",
    "Family of man and boy": "👨‍👦",
    "Family of man, boy, and boy": "👨‍👦‍👦",
    "Family of man and girl": "👨‍👧",
    "Family of man, girl, and boy": "👨‍👧‍👦",
    "Family of man, girl, and girl": "👨‍👧‍👧",
    "Family of woman, and boy": "👩‍👦",
    "Family of woman, boy, and boy": "👩‍👦‍👦",
    "Family of woman, and girl": "👩‍👧",
    "Family of woman, girl, and boy": "👩‍👧‍👦",
    "Family of woman, girl, and girl": "👩‍👧‍👧",
    "People holding hands": "🧑‍🤝‍🧑",
    "Women holding hands": "👭",
    "Woman and man holding hands": "👫",
    "Men holding hands": "👬",
    "Woman and man kissing": "👩‍❤️‍💋‍👨",
    "Man and man kissing": "👨‍❤️‍💋‍👨",
    "Woman and woman kissing": "👩‍❤️‍💋‍👩",
    "Woman and man couple": "👩‍❤️‍👨",
    "Man and man couple": "👨‍❤️‍👨",
    "Woman and woman couple": "👩‍❤️‍👩",
    "Couple with heart": "💑",
    "Person speaking": "🗣",
    "Bust in silhouhette": "👤",
    "Busts in silhouette": "👥",
    "People hugging": "🫂",
    "Monkey face": "🐵",
    "Monkey": "🐒",
    "Gorilla": "🦍",
    "Orangutan": "🦧",
    "Dog face": "🐶",
    "Dog": "🐕",
    "Guide dog": "🦮",
    "Service dog": "🐕‍🦺",
    "Poodle": "🐩",
    "Wolf": "🐺",
    "Fox": "🦊",
    "Racoon": "🦝",
    "Cat face": "🐱",
    "Cat": "🐈",
    "Black Cat": "🐈‍⬛",
    "Lion": "🦁",
    "Tiger face": "🐯",
    "Tiger": "🐅",
    "Leopard": "🐆",
    "Horse face": "🐴",
    "Horse": "🐎",
    "Unicorn": "🦄",
    "Zebra": "🦓",
    "Deer": "🦌",
    "Bison": "🦬",
    "Cow face": "🐮",
    "Cow": "🐄",
    "Ox": "🐂",
    "Water buffalo": "🐃",
    "Pig face": "🐷",
    "Pig": "🐖",
    "Boar": "🐗",
    "Pig nose": "🐽",
    "Ram": "🐏",
    "Ewe": "🐑",
    "Goat": "🐐",
    "Camel": "🐪",
    "Two hump camel": "🐫",
    "Llama": "🦙",
    "Giraffe": "🦒",
    "Elephant": "🐘",
    "Mammoth": "🦣",
    "Rhinoceros": "🦏",
    "Hippopotamus": "🦛",
    "Mouse face": "🐭",
    "Mouse": "🖱",
    "Rat": "🐀",
    "Hamster": "🐹",
    "Rabbit face": "🐰",
    "Rabbit": "🐇",
    "Chipmunk": "🐿",
    "Beaver": "🦫",
    "Hedgehog": "🦔",
    "Bat": "🦇",
    "Bear": "🐻",
    "Polar bear": "🐻‍❄️",
    "Koala": "🐨",
    "Panda": "🐼",
    "Sloth": "🦥",
    "Otter": "🦦",
    "Skunk": "🦨",
    "Kangaroo": "🦘",
    "Badger": "🦡",
    "Paw prints": "🐾",
    "Turkey": "🦃",
    "Chicken": "🐔",
    "Rooster": "🐓",
    "Hatching": "🐣",
    "Baby chick": "🐤",
    "Front-facing chick": "🐥",
    "Bird": "🐦",
    "Black bird": "🐦‍⬛",
    "Penguin": "🐧",
    "Dove": "🕊",
    "Eagle": "🦅",
    "Duck": "🦆",
    "Swan": "🦢",
    "Owl": "🦉",
    "Dodo": "🦤",
    "Feather": "🪶",
    "Flamingo": "🦩",
    "Peacock": "🦜",
    "Frog": "🐸",
    "Crocodile": "🐊",
    "Turtle": "🐢",
    "Lizard": "🦎",
    "Snake": "🐍",
    "Dragon face": "🐲",
    "Dragon": "🐉",
    "Sauropod": "🦕",
    "Tyrannosaurus": "🦖",
    "Spouting whale": "🐳",
    "Whale": "🐋",
    "Dolphin": "🐬",
    "Seal": "🦭",
    "Fish": "🐟",
    "Tropical fish": "🐠",
    "Blowfish": "🐡",
    "Shark": "🦈",
    "Octopus": "🐙",
    "Spiral shell": "🐚",
    "Snail": "🐌",
    "Butterfly": "🦋",
    "Bug": "🐛",
    "Ant": "🐜",
    "Honeybee": "🐝",
    "Beetle": "🪲",
    "Lady Beetle": "🐞",
    "Cricket": "🏏",
    "Cockroach": "🪳",
    "Spider": "🕷",
    "Spider web": "🕸",
    "Scorpion": "🦂",
    "Mosquito": "🦟",
    "Fly": "🪰",
    "Worm": "🪱",
    "Microbe": "🦠",
    "Bouquet": "💐",
    "Cherry blossom": "🌸",
    "White flower": "💮",
    "Rosette": "🏵",
    "Rose": "🌹",
    "Wilted flower": "🥀",
    "Hibiscus": "🌺",
    "Sunflower": "🌻",
    "Blossom": "🌼",
    "Tulip": "🌷",
    "Seedling": "🌱",
    "Potted plant": "🪴",
    "Evergreen tree": "🌲",
    "Deciduous plant": "🌳",
    "Palm tree": "🌴",
    "Cactus": "🌵",
    "Sheaf of rice": "🌾",
    "Herb": "🌿",
    "Shamrock": "☘",
    "Four leaf clover": "🍀",
    "Maple leaf": "🍁",
    "Fallen leaf": "🍂",
    "Leaf fluttering in wind": "🍃",
    "Empty nest": "🪹",
    "Nest with eggs": "🪺",
    "Grapes": "🍇",
    "Melon": "🍈",
    "Water melon": "🍉",
    "Tangerine": "🍊",
    "Lime": "🍋",
    "Banana": "🍌",
    "Pineapple": "🍍",
    "Mango": "🥭",
    "Red apple": "🍎",
    "Green apple": "🍏",
    "Pear": "🍐",
    "Peach": "🍑",
    "Cherries": "🍒",
    "Strawberries": "🍓",
    "Blueberries": "🫐",
    "Kiwi fruit": "🥝",
    "Tomato": "🍅",
    "Olive": "🫒",
    "Coconut": "🥥",
    "Avocado": "🥑",
    "Eggplant": "🍆",
    "Potato": "🥔",
    "Carrot": "🥕",
    "Corn": "🌽",
    "Pepper": "🌶",
    "Bell pepper": "🫑",
    "Cucumber": "🥒",
    "Leafy green": "🥬",
    "Broccoli": "🥦",
    "Garlic": "🧄",
    "Onion": "🧅",
    "Mushroom": "🍄",
    "Peanuts": "🥜",
    "Beans": "🫑",
    "Chestnut": "🌰",
    "Bread": "🍞",
    "Croissant": "🥐",
    "Baguette bread": "🥖",
    "Flat bread": "🫓",
    "Pretzel": "🥨",
    "Bagel": "🥯",
    "Pancake": "🥞",
    "Waffle": "🧇",
    "Cheese wedge": "🧀",
    "Meat with bone": "🍖",
    "Poultry leg": "🍗",
    "Cut of meat": "🥩",
    "Bacon": "🥓",
    "Hamburger": "🍔",
    "French fries": "🍟",
    "Pizza": "🍕",
    "Hot dog": "🌭",
    "Sandwich": "🥪",
    "Taco": "🌮",
    "Burrito": "🌯",
    "Tamale": "🫔",
    "Stuffed flatbread": "🥙",
    "Falafel": "🧆",
    "Egg": "🥚",
    "Cooking": "🍳",
    "Shallow pan of food": "🥘",
    "Pot of food": "🍲",
    "Fondue": "🫕",
    "Bowl with food": "🥣",
    "Green salad": "🥗",
    "Popcorn": "🍿",
    "Butter": "🧈",
    "Salt": "🧂",
    "Canned food": "🥫",
    "Bento box": "🍱",
    "RIce cracker": "🍘",
    "Rice ball": "🍙",
    "Cooked rice": "🍚",
    "Curry rice": "🍛",
    "Steaming bowl": "🍜",
    "Spaghetti": "🍝",
    "Roasted sweet potato": "🍠",
    "Oden": "🍢",
    "Sushi": "🍣",
    "Fried shrimp": "🍤",
    "Fish cake with swiri": "🍥",
    "Moon cake": "🥮",
    "Dango": "🍡",
    "Dumpling": "🥟",
    "Fortune cookie": "🥠",
    "Take out box": "🥡",
    "Crab": "🦀",
    "Lobster": "🦞",
    "Shrimp": "🦐",
    "Squid": "🦑",
    "Oyster": "🦪",
    "Ice cream": "🍨",
    "Shaved ice cream": "🍧",
    "Soft ice cream": "🍦",
    "Doughnut": "🍩",
    "Cookie": "🍪",
    "Birthday cake": "🎂",
    "Short cake": "🍰",
    "Cup cake": "🧁",
    "Pie": "🥧",
    "Chocolate": "🍫",
    "Candy": "🍬",
    "Lollipop": "🍭",
    "Custard": "🍮",
    "Honey pot": "🍯",
    "Baby bottle": "🍼",
    "Glass of milk": "🥛",
    "Hot beverage": "☕",
    "Teapot": "🫖",
    "Teacup without handle": "🍵",
    "Sake": "🍶",
    "Bottle with poppin cork": "🍾",
    "Wine glass": "🍷",
    "Cocktail glass": "🍸",
    "Tropical drink": "🍹",
    "Beer mug": "🍺",
    "Clinking beer mug": "🍻",
    "Clinking glasses": "🥂",
    "Tumbler glass": "🥃",
    "Cup with strawberry": "🥤",
    "Bubble tea": "🧋",
    "Beverage box": "🧃",
    "Mate drink": "🧉",
    "Ice": "🧊",
    "Chopsticks": "🥢",
    "Fork and knife with plate": "🍽",
    "Fork and knife": "🍴",
    "Spoon": "🥄",
    "Kitchen knife": "🔪",
    "Jar": "🧋",
    "Amphora": "🏺",
    "Globe showing Africa and Europe": "🌍",
    "Globe showing Americas": "🌎",
    "Globe showing Asia and Australia": "🌏",
    "Globe with meridians": "🌐",
    "World map": "🗺",
    "Compass": "🧭",
    "Mountain": "⛰",
    "Snowcap mountain": "🏔",
    "Volcanic mountain": "🌋",
    "Fuji mountain": "🗻",
    "Camping": "🏕",
    "Beach with umbrella": "🏖",
    "Desert": "🏜",
    "Desertified island": "🏝",
    "National park": "🏞",
    "Stadium": "🏟",
    "Classical building": "🏛",
    "Building construction": "🏗",
    "Brick": "🧱",
    "Rock": "🪨",
    "Wood": "🪵",
    "Hut": "🛖",
    "Houses": "🏘",
    "Derelict house": "🏚",
    "House": "🏠",
    "House with garden": "🏡",
    "Office building": "🏢",
    "Japanese office": "🏣",
    "Post office": "🏤",
    "Hospital": "🏥",
    "Bank": "🏦",
    "Hotel": "🏨",
    "Love hotel": "🏩",
    "Convenience store": "🏪",
    "School": "🏫",
    "Department": "🏬",
    "Factory": "🏭",
    "Japanese castle": "🏯",
    "Castle": "🏰",
    "Wedding house": "💒",
    "Tokyo tower": "🗼",
    "Statue of liberty": "🗽",
    "Church": "⛪",
    "Mosque": "🕌",
    "Hindu temple": "🛕",
    "Synagogue": "🕍",
    "Shinto shrine": "⛩",
    "Kaaba": "🕋",
    "Fountain": "⛲",
    "Tent": "⛺",
    "Foggy": "🌁",
    "Night with starrs": "🌃",
    "Citscape": "🏙",
    "Sunrise": "🌅",
    "Sunrise over mountains": "🌄",
    "Cityscape at dusk": "🌆",
    "Sunset": "🌇",
    "Bridge at night": "🌉",
    "Hot springs": "♨",
    "Carousel horse": "🎠",
    "Ferris wheel": "🎡",
    "Roller coaster": "🎢",
    "Barber poll": "💈",
    "Circus tent": "🎪",
    "Locomotive": "🚂",
    "Railway car": "🚃",
    "High speed train": "🚄",
    "Bullet train": "🚅",
    "Train": "🚆",
    "Metro": "🚇",
    "Light rail": "🚈",
    "Station": "🚉",
    "Tram": "🚊",
    "Monorail": "🚝",
    "Mountain railway": "🚞",
    "Tram car": "🚋",
    "us": "🚌",
    "Oncoming bus": "🚍",
    "Trolley bus": "🚎",
    "Minibus": "🚐",
    "Ambulance": "🚑",
    "Fire engine": "🚒",
    "Police car": "🚓",
    "Oncoming police car": "🚔",
    "Taxi": "🚕",
    "Oncoming taxi": "🚖",
    "Automobile": "🚗",
    "Oncoming automobile": "🚘",
    "Sport utility vehicle": "🚙",
    "Pickup truck": "🛻",
    "Delivery truck": "🚚",
    "Articulated lorry": "🚛",
    "Tractor": "🚜",
    "Racing car": "🏎",
    "Motorcycle": "🏍",
    "Scooter": "🛵",
    "Manual wheelchair": "🦽",
    "Motorized wheelchair": "🦼",
    "Hourglass done": "⌛",
    "Hourglass starting": "⏳",
    "Watch": "⌚",
    "Alarm": "⏰",
    "Stopwatch": "⏱",
    "Timer clock": "⏲",
    "Mantelpiece clock": "🕰",
    "Twelve O'clock": "🕛",
    "Twelve-thirty": "🕧",
    "One O'clock": "🕐",
    "One-thirty": "🕜",
    "Two O'clock": "🕑",
    "Two-thirty": "🕝",
    "Three O'clock": "🕒",
    "Three-thirty": "🕞",
    "Four O'clock": "🕓",
    "Four-thirty": "🕟",
    "Five O'clock": "🕔",
    "Five-thirty": "🕠",
    "Six O'clock": "🕕",
    "Six-thirty": "🕡",
    "Seven O'clock": "🕖",
    "Seven-thirty": "🕢",
    "Eight O'clock": "🕗",
    "Eight-thirty": "🕣",
    "Nine O'clock": "🕘",
    "Nine-thirty": "🕤",
    "Ten O'clock": "🕙",
    "Ten-thirty": "🕥",
    "Eleven O'clock": "🕚",
    "Eleven-thirty": "🕦",
    "New moon": "🌑",
    "Waxing crescent moon": "🌒",
    "First quarter moon": "🌓",
    "Waxing gibbous moon": "🌔",
    "Full moon": "🌕",
    "Waning gibbous moon": "🌖",
    "Last quarter moon": "🌗",
    "Waning crescent moon": "🌘",
    "Crescent moon": "🌙",
    "New moon face": "🌚",
    "First quarter moon face": "🌛",
    "Last quartermoon face": "🌜",
    "Thermometer": "🌡",
    "Sun": "☀",
    "Full moon face": "🌝",
    "Sun with face": "🌞",
    "Ringed planet": "🪐",
    "Star": "⭐",
    "Glowing star": "🌟",
    "Shooting star": "🌠",
    "Milky way": "🌌",
    "Cloud": "☁",
    "Sun behind cloud": "⛅",
    "Cloud with lighting and rain": "⛈",
    "Sun behind small cloud": "🌤",
    "Sun behind large cloud": "🌥",
    "Sun behind rain cloud": "🌦",
    "Cloud with rain": "🌧",
    "Cloud with snow": "🌨",
    "Cloud with lighting": "🌩",
    "Tornado": "🌪",
    "Fog": "🌫",
    "Wind face": "🌬",
    "Cyclone": "🌀",
    "Rainbow": "🌈",
    "Closed umbrella": "🌂",
    "Umbrella": "☂",
    "Umbrella with raindrops": "☔",
    "Umbrella on ground": "⛱",
    "High voltage": "⚡",
    "Snowflake": "❄",
    "Snowman": "☃",
    "Snowman without snow": "⛄",
    "Comet": "☄",
    "Fire": "🔥",
    "Droplet": "💧",
    "Water wave": "🌊",
    "Jack-o-lantern": "🎃",
    "Christmas tree": "🎄",
    "Fireworks": "🎆",
    "Sparkler": "🎇",
    "Firecracker": "🧨",
    "Sparkles": "✨",
    "Baloon": "🎈",
    "Party popper": "🎉",
    "Confetti ball": "🎊",
    "Tanabata tree": "🎋",
    "Pine decoration": "🎍",
    "Japanese dolls": "🎎",
    "Carp streamer": "🎏",
    "Moon viewing ceremony": "🎑",
    "Red envelope": "🧧",
    "Ribbon": "🎀",
    "Wrapped gift": "🎁",
    "Reminder ribbon": "🎗",
    "Admission ticket": "🎟",
    "Ticket": "🎫",
    "Military medal": "🎖",
    "Trophy": "🏆",
    "Sports medal": "🏅",
    "Gold medal - first position": "🥇",
    "Silver medal - second position": "🥈",
    "Bronze medal - third position": "🥉",
    "Soccer ball": "⚽",
    "Baseball": "⚾",
    "Softball": "🥎",
    "Basketball": "🏀",
    "Volleyball": "🏐",
    "American football": "🏈",
    "Rugby": "🏉",
    "Tennis": "🎾",
    "Flying disk": "🥏",
    "Bowling": "🎳",
    "Field hockey": "🏑",
    "Ice hockey": "🏒",
    "Lacrosse": "🥍",
    "Ping pong": "🏓",
    "Badminton": "🏸",
    "Boxing glove": "🥊",
    "Martial arts uniform": "🥋",
    "Goal net": "🥅",
    "Flag in a hole": "⛳",
    "Ice skate": "⛸",
    "Fishing pole": "🎣",
    "Diving mask": "🤿",
    "Running shirt": "🎽",
    "Skis": "🎿",
    "Sled": "🛷",
    "Curling stone": "🥌",
    "Bullseye": "🎯",
    "Yo-yo": "🪀",
    "Kite": "🪁",
    "8 ball": "🎱",
    "Crystal ball": "🔮",
    "Magic wand": "🪄",
    "Nazar amulet": "🧿",
    "Hamsa": "🪬",
    "Video game pad": "🎮",
    "Joystick": "🕹",
    "Slot machine": "🎰",
    "Game die": "🎲",
    "Puzzle piece": "🧩",
    "Teddy bear": "🧸",
    "Piñata": "🪅",
    "Nesting doll": "🪆",
    "Spade suit": "♠",
    "Heart suit": "♥",
    "Club suit": "♣",
    "Chess pawn": "♟",
    "Joker": "🃏",
    "Mahjong red dragon": "🀄",
    "Flower playing cards": "🎴",
    "Performing arts": "🎭",
    "Framed picture": "🖼",
    "Artist palette": "🎨",
    "Thread": "🧵",
    "Sewing needle with thread": "🪡",
    "Yarn": "🧶",
    "Knot": "🪢",
    "Glasses": "👓",
    "Sunglasses": "🕶",
    "Goggles": "🥽",
    "Lab coat": "🥼",
    "Safety vest": "🦺",
    "Necktie": "👔",
    "T-shirt": "👕",
    "Jeans": "👖",
    "Scarf": "🧣",
    "Gloves": "🧤",
    "Coat": "🧥",
    "Socks": "🧦",
    "Dress": "👗",
    "Kimono": "👘",
    "Sari": "🥻",
    "One piece suit": "🩱",
    "Briefs": "🩲",
    "Shorts": "🩳",
    "Bikini": "👙",
    "Woman's shirt": "👚",
    "Purse": "👛",
    "Handbag": "👜",
    "Clutch bag": "👝",
    "Shopping bags": "🛍",
    "Backpack": "🎒",
    "Thong sandals": "🩴",
    "Man's shoe": "👞",
    "Running shoe": "👟",
    "Hiking boot": "🥾",
    "Flat shoe": "🥿",
    "High-heeled shoe": "👠",
    "Woman's sandal": "👡",
    "Ballet shoes": "🩰",
    "Woman's boot": "👢",
    "Crown": "👑",
    "Woman's hat": "👒",
    "Top hat": "🎩",
    "Graduation cap": "🎓",
    "Billed cap": "🧢",
    "Military helmet": "🪖",
    "Rescue worker's helmet": "⛑",
    "Prayer beads": "📿",
    "Lipstick": "💄",
    "Ring": "💍",
    "Gemstone": "💎",
    "Muted speaker": "🔇",
    "Low volume speaker": "🔈",
    "Mid volume speaker": "🔉",
    "High volume speaker": "🔊",
    "Loudspeaker": "📢",
    "Megaphone": "📣",
    "Postal horn": "📯",
    "Bell": "🔔",
    "Bell with slash": "🔕",
    "Musical score": "🎼",
    "Musical note": "🎵",
    "Musical notes": "🎶",
    "Studio microphone": "🎙",
    "Level slider": "🎚",
    "Control knobs": "🎛",
    "Microphone": "🎤",
    "Headphone": "🎧",
    "Radio": "📻",
    "Saxophone": "🎷",
    "Accordion": "🪗",
    "Guitar": "🎸",
    "Musical keyboard": "🎹",
    "Trumpet": "🎺",
    "Violin": "🎻",
    "Banjo": "🪕",
    "Drum": "🥁",
    "Long drum": "🪘",
    "Mobile phone": "📱",
    "Mobile phone with arrow": "📲",
    "Telephone": "☎",
    "Telephone receiver": "📞",
    "Pager": "📟",
    "Fax machine": "📠",
    "Full battery": "🔋",
    "Low battery": "🪫",
    "Electric plug": "🔌",
    "Laptop": "💻",
    "Desktop computer": "🖥",
    "Printer": "🖨",
    "Keyboard": "⌨",
    "Trackball": "🖲",
    "Computer disk": "💽",
    "Floppy disk": "💾",
    "Optical disk": "💿",
    "DVD": "📀",
    "Abacus": "🧮",
    "Movie camera": "🎥",
    "Film frames": "🎞",
    "Film Projector": "📽",
    "Clapper board": "🎬",
    "Television": "📺",
    "Camera": "📷",
    "Camera with flash": "📸",
    "Video camera": "📹",
    "Video cassette": "📼",
    "Magnifying glass tilted left": "🔍",
    "Magnifying glass tilted right": "🔎",
    "Candle": "🕯",
    "Light bulb": "💡",
    "Flashlight": "🔦",
    "Red pepper lantern": "🏮",
    "Diya lamp": "🪔",
    "Notebook with decorative cover": "📔",
    "Closed notebook": "📕",
    "Opened notebook": "📖",
    "Green book": "📗",
    "Blue book": "📘",
    "Orange book": "📙",
    "Orange books": "📚",
    "Notebook": "📓",
    "Ledger": "📒",
    "Page with curl": "📃",
    "Scroll": "📜",
    "Page facing up": "📄",
    "Newspaper": "📰",
    "Rolled-up newspaper": "🗞",
    "Bookmark tabs": "📑",
    "Bookmark": "🔖",
    "Label": "🏷",
    "Money bag": "💰",
    "Coin": "🪙",
    "Yen banknote": "💴",
    "Dollar banknote": "💵",
    "Euro banknote": "💶",
    "Pound banknote": "💷",
    "Money with wings": "💸",
    "Credit card": "💳",
    "Receipt": "🧾",
    "Chart increase woth Yen": "💹",
    "Envelope": "✉",
    "e-mail": "📧",
    "Envelope with arrow": "📩",
    "Outbox tray": "📤",
    "Inbox tray": "📥",
    "Package": "📦",
    "Closed mailbox with raised flag": "📫",
    "Closed mailbox with lowered flag": "📪",
    "Open mailbox with raised flag": "📬",
    "Open mailbox with lowered flag": "📭",
    "Postbox": "📮",
    "Ballot box with ballot": "🗳",
    "Pencil": "✏",
    "Black nib": "✒",
    "Fountain pen": "🖋",
    "Pen": "🖊",
    "Paintbrush": "🖌",
    "Crayon": "🖍",
    "Memo": "📝",
    "Briefcase": "💼",
    "File folder": "📁",
    "Open the folder": "📂",
    "Card index dividers": "🗂",
    "Calender": "📅",
    "Tear off calender": "📆",
    "Card index": "📇",
    "Increasing chart": "📈",
    "Decreasing chart": "📉",
    "Bar chart": "📊",
    "Clipboard": "📋",
    "Pushpin": "📌",
    "Round pushpin": "📍",
    "Paperclip": "📎",
    "Linked paperclips": "🖇",
    "Straight ruler": "📏",
    "Triangular ruler": "📐",
    "Scissors": "✂",
    "Card file box": "🗃",
    "File cabinet": "🗄",
    "Waste basket": "🗑",
    "Locked": "🔒",
    "Unlocked": "🔓",
    "Locked with pen": "🔏",
    "Locked with key": "🔐",
    "Key": "🔑",
    "Old key": "🗝",
    "Hammer": "🔨",
    "Axe": "🪓",
    "Pick": "⛏",
    "Hammer and pick": "⚒",
    "Hammer and wrench": "🛠",
    "Sword": "🗡",
    "Crossed swords": "⚔",
    "Water gun": "🔫",
    "Boomerang": "🪃",
    "Bow and arrow": "🏹",
    "Shield": "🛡",
    "Carpentry saw": "🪚",
    "Wrench": "🔧",
    "Screwdriver": "🪛",
    "Bolt and nut": "🔩",
    "Wheel": "⚙",
    "Clamp": "🗜",
    "Balance scale": "⚖",
    "White cane": "🦯",
    "Link": "🔗",
    "Chains": "⛓",
    "Hook": "🪝",
    "Toolbox": "🧰",
    "Magnet": "🧲",
    "Ladder": "🪜",
    "Alembic": "⚗",
    "Test tube": "🧪",
    "Petri dish": "🧫",
    "DNA": "🧬",
    "Microscope": "🔬",
    "Telescope": "🔭",
    "Satelite antenna": "📡",
    "Syringe": "💉",
    "A droplet of blood": "🩸",
    "Pill": "💊",
    "Adhesive bandage": "🩹",
    "Crutch": "🩼",
    "Stethoscope": "🩺",
    "X-ray": "🩻",
    "Door": "🚪",
    "Elevator": "🛗",
    "Mirror": "🪞",
    "Window": "🪟",
    "Bed": "🛏",
    "Couch and lamp": "🛋",
    "Chair": "🪑",
    "Toilet": "🚽",
    "Plunger": "🪠",
    "Shower": "🚿",
    "Bathtub": "🛁",
    "Mouse trap": "🪤",
    "Razor": "🪒",
    "Lotion bottle": "🧴",
    "Safety pin": "🧷",
    "Broom": "🧹",
    "Basket": "🧺",
    "Roll of paper": "🧻",
    "Bucket": "🪣",
    "Soap": "🧼",
    "Bubbles": "🫧",
    "Toothbrush": "🪥",
    "Sponge": "🧽",
    "Fire extinguisher": "🧯",
    "Shopping cart": "🛒",
    "Cigarette": "🚬",
    "Casket": "⚰",
    "Headstone": "🪦",
    "Funeral urn": "⚱",
    "Moai": "🗿",
    "Placard": "🪧",
    "ID Card": "🪪",
    "ATM Sign": "🏧",
    "Litter in bin": "🚮",
    "Portable water": "🚰",
    "Wheelchair symbol": "♿",
    "Men's room symbol": "🚹",
    "Women's room symbol": "🚺",
    "Restroom symbol": "🚻",
    "Baby symbol": "🚼",
    "Water closet": "🚾",
    "Passport control": "🛂",
    "Customs": "🛃",
    "Baggage claim": "🛄",
    "Left laugage": "🛅",
    "Warning": "⚠",
    "Children crossing": "🚸",
    "No entry": "⛔",
    "Prohibited": "🚫",
    "No bicycles": "🚳",
    "No smoking": "🚭",
    "No littering": "🚯",
    "Non-portable water": "🚱",
    "No pedestrians": "🚷",
    "No mobile phones": "📵",
    "No one under 18": "🔞",
    "Radioactive": "☢",
    "Biohazard": "☣",
    "Up Arrow": "⬆",
    "Up-right arrow": "↗",
    "Right arrow": "➡",
    "Down-right arrow": "↘",
    "Down arrow": "⬇",
    "Down-left arrow": "↙",
    "Left arrow": "↔",
    "Up-left arrow": "↖",
    "Up-down arrow": "↕",
    "Right arrow curving left": "↩",
    "Left arrow curving right": "↪",
    "Right arrow curving up": "⤴",
    "Right arrow curving down": "⤵",
    "Clockwise vertical arrow": "🔃",
    "Counterclockwise arrows button": "🔄",
    "Back arrow": "🔙",
    "End arrow": "🔚",
    "On arrow": "🔛",
    "Soon arrow": "🔜",
    "Top arrow": "🔝",
    "Place of worship": "🛐",
    "Atom symbol": "⚛",
    "OM": "🕉",
    "Star of David": "✡",
    "Wheel of Dharma": "☸",
    "Yin yang": "☯",
    "Latin cross": "✝",
    "Orthodox cross": "☦",
    "Star and cresent moon": "☪",
    "Peace": "☮",
    "Menorah": "🕎",
    "Six-pointed star": "🔯",
    "Aries": "♈",
    "Taurus": "♉",
    "Gemini": "♊",
    "Cancer": "♋",
    "Leo": "♌",
    "Virgo": "♍",
    "Libra": "♎",
    "Scorpio": "♏",
    "Sagittarius": "♐",
    "Capricon": "♑",
    "Acquarius": "♒",
    "Pisces": "♓",
    "Ophiucus": "⛎",
    "Shuffle tracks": "🔀",
    "Repeat all": "🔁",
    "Repeat one": "🔂",
    "Play": "▶",
    "Pause": "⏸",
    "Fast-forward": "⏩",
    "Next track": "⏭",
    "Play or pause": "⏯",
    "Reverse": "◀",
    "Fast-reverse": "⏪",
    "Previous track": "⏮",
    "Upwards": "🔼",
    "Fast-up": "⏫",
    "Downwards": "🔽",
    "Fast down": "⏬",
    "Stop": "⏹",
    "Record": "⏺",
    "Eject": "⏏",
    "Cinema": "🎦",
    "Dim": "🔅",
    "Bright": "🔆",
    "Network antenna bars": "📶",
    "Vibration mode": "📳",
    "Mobile phone off": "📴",
    "Female": "♀",
    "Male": "♂",
    "Transgender": "⚧",
    "Times": "✖",
    "Plus": "➕",
    "Minus": "➖",
    "Divide": "➗",
    "Equals": "🟰",
    "Infinity": "♾",
    "Double exclamation": "‼",
    "Exclamation and question mark": "⁉",
    "Red question mark": "❓",
    "White question mark": "❔",
    "Red exclamation mark": "❗",
    "White exclamation mark": "❕",
    "Wavy dash": "〰",
    "Currency exchange": "💱",
    "Heavy green dollar sign": "💲",
    "Medical symbol": "⚕",
    "Recycling symbol": "♻",
    "Fleur-de-lis": "⚜",
    "Trident": "🔱",
    "Name badge": "📛",
    "Japanese symbol for beginner": "🔰",
    "Hollow red circle": "⭕",
    "Green box with checkmark": "✅",
    "Blue box with checkmark": "☑",
    "Checkmark": "✔",
    "Crossmark": "❌",
    "Green crossmark": "❎",
    "Curly loop": "➰",
    "Double curly loop": "➿",
    "Part alternation mark": "〽",
    "Eight-spoked asterisk": "✳",
    "Eight-pointed star": "✴",
    "Sparkle": "❇",
    "Copyright symbol": "©",
    "Registered": "®",
    "Trademark": "™",
    "# Keycap": "#️⃣",
    "* Keycap": "*️⃣",
    "0 Keycap": "0️⃣",
    "1 Keycap": "1️⃣",
    "2 Keycap": "2️⃣",
    "3 Keycap": "3️⃣",
    "4 Keycap": "4️⃣",
    "5 Keycap": "5️⃣",
    "6 Keycap": "6️⃣",
    "7 Keycap": "7️⃣",
    "8 Keycap": "8️⃣",
    "9 Keycap": "9️⃣",
    "10 Keycap": "🔟",
    "Input Latin uppercase": "🔠",
    "Input Latin lowercase": "🔡",
    "Input numbers": "🔢",
    "Input symbols": "🔣",
    "Input Latin letters": "🔤",
    "A blood type": "🅰",
    "AB blood type": "🆎",
    "B blood type": "🅱",
    "O blood type": "🅾",
    "CL button": "🆑",
    "Cool button": "🆒",
    "Free button": "🆓",
    "Info button": "ℹ",
    "ID button": "🆔",
    "Circled M": "Ⓜ",
    "New button": "🆕",
    "NG button": "🆖",
    "OK button": "🆗",
    "P button": "🅿",
    "SOS button": "🆘",
    "UP! button": "🆙",
    "VS Button": "🆚",
    "Japanese here button": "🈁",
    "Japanese service charge button": "🈂",
    "Japanese monthly amount button": "🈷",
    "Japanese not free of charge button": "🈶",
    "Japanese reserved button": "🈯",
    "Japanese bargain button": "🉐",
    "Japanese discount button": "🈹",
    "Japanese free of charge button": "🈚",
    "Japanese prohibited button": "🈲",
    "Japanese acceptable button": "🉑",
    "Japanese application button": "🈸",
    "Japanese passing grade button": "🈴",
    "Japanese vacancy button": "🈳",
    "Japanese congratulations button": "㊗",
    "Japanese secret button": "㊙",
    "Japanese open for business button": "🈺",
    "Japanese no vacancy button": "🈵",
    "Red circle": "🔴",
    "Orange circle": "🟠",
    "Yellow circle": "🟡",
    "Green circle": "🟢",
    "Blue circle": "🔵",
    "Purple circle": "🟣",
    "Brown circle": "🟤",
    "Black circle": "⚫",
    "White circle": "⚪",
    "Red square": "🟥",
    "Orange square": "🟧",
    "Yellow square": "🟨",
    "Green square": "🟩",
    "Blue square": "🟦",
    "Purple square": "🟪",
    "Brown square": "🟫",
    "Black square": "⬛",
    "White square": "⬜",
    "Large orange diamond": "🔶",
    "Large blue diamond": "🔷",
    "Small orange diamond": "🔸",
    "Small blue diamond": "🔹",
    "Red triangle pointed up": "🔺",
    "Red triangle pointed down": "🔻",
    "Diamond with a dot": "💠",
    "Radio button": "🔘",
    "White square button": "🔳",
    "Black square button": "🔲",
    "Chequered flag": "🏁",
    "Triangular flag": "🚩",
    "Crossed flag": "🎌",
    "Black flag": "🏴",
    "White flag": "🏳",
    "Rainbow flag": "🏳️‍🌈",
    "Transgender Flag": "🏳️‍⚧️",
    "Pirate flag": "🏴‍☠️",
    "Ascension Island flag": "🇦🇨",
    "Andorra flag": "🇦🇩",
    "UAE flag": "🇦🇪",
    "Afghanistan flag": "🇦🇫",
    "Antigua & Barbuda flag": "🇦🇬",
    "Anguilla flag": "🇦🇮",
    "Albania": "🇦🇱",
    "Algeria flag": "🇩🇿",
    "Armenia flag": "🇦🇲",
    "Angola flag": "🇦🇴",
    "Antarctica flag": "🇦🇶",
    "Argentina flag": "🇦🇷",
    "American Samoa flag": "🇦🇸",
    "Austria flag": "🇦🇹",
    "Australia flag": "🇦🇺",
    "Aruba flag": "🇦🇼",
    "Åland Islands flag": "🇦🇽",
    "Azerbaijan flag": "🇦🇿",
    "Bosnia & Herzegovina flag": "🇧🇦",
    "Bangladesh flag": "🇧🇩",
    "Belgium flag": "🇧🇪",
    "Burkina Faso flag": "🇧🇫",
    "Bulgaria flag": "🇧🇬",
    "Bahrain flag": "🇧🇭",
    "Burundi flag": "🇧🇮",
    "Benin Republic flag": "🇧🇯",
    "St. Barthélemy flag": "🇧🇱",
    "Bermuda flag": "🇧🇲",
    "Brunei flag": "🇧🇳",
    "Bolivia flag": "🇧🇴",
    "Caribbean Netherlands flag": "🇧🇶",
    "Brazil flag": "🇧🇷",
    "Bahamas flag": "🇧🇸",
    "Bhutan flag": "🇧🇹",
    "Bouvet Island flag": "🇧🇻",
    "Botswana flag": "🇧🇼",
    "Belarus flag": "🇧🇾",
    "Belize flag": "🇧🇿",
    "Canada flag": "🇨🇦",
    "Cocos (Keeling) Islands flag": "🇨🇨",
    "DR Congo flag": "🇨🇩",
    "Central African Republic flag": "🇨🇫",
    "Congo Brazzaville flag": "🇨🇬",
    "Switzerland flag": "🇨🇭",
    "Côte d’Ivoire flag": "🇨🇮",
    "Cook Islands flag": "🇨🇰",
    "Chile flag": "🇨🇱",
    "Cameroon flag": "🇨🇲",
    "China flag": "🇨🇳",
    "Columbia flag": "🇨🇴",
    "Clipperton Island flag": "🇨🇵",
    "Costa Rica flag": "🇨🇷",
    "Cuba flag": "🇨🇺",
    "Cape Verde flag": "🇨🇻",
    "Curaçao flag": "🇨🇼",
    "Christmas Island flag": "🇨🇽",
    "Cyprus flag": "🇨🇾",
    "Czech Republic flag": "🇨🇿",
    "Germany flag": "🇩🇪",
    "Diego Garcia flag": "🇩🇬",
    "Djibouti flag": "🇩🇯",
    "Denmark flag": "🇩🇰",
    "Dominica flag": "🇩🇲",
    "Dominican Republic flag": "🇩🇴",
    "Ceuta & Melilla flag": "🇪🇦",
    "Ecuador flag": "🇪🇨",
    "Estonia flag": "🇪🇪",
    "Egypt flag": "🇪🇬",
    "Western Sahara flag": "🇪🇭",
    "Eritre flag": "🇪🇷",
    "Spain flag": "🇪🇸",
    "Ethiopia flag": "🇪🇹",
    "European Union flag": "🇪🇺",
    "Finalnd flag": "🇫🇮",
    "Fiji Island flag": "🇫🇯",
    "Falkland Islands flag": "🇫🇰",
    "Micronesia flag": "🇫🇲",
    "Faroe Islands flag": "🇫🇴",
    "France flag": "🇫🇷",
    "Gabon flag": "🇬🇦",
    "United Kingdom flag": "🇬🇧",
    "Grenada flag": "🇬🇩",
    "Georgia flag": "🇬🇪",
    "French Guiana flag": "🇬🇫",
    "Guernsey flag": "🇬🇬",
    "Ghana flag": "🇬🇭",
    "Gibraltar flag": "🇬🇮",
    "Greenland flag": "🇬🇱",
    "Gambia flag": "🇬🇲",
    "Guinea flag": "🇬🇳",
    "Guadeloupe flag": "🇬🇵",
    "Equatorial Guinea flag": "🇬🇶",
    "Greece flag": "🇬🇷",
    "South Georgia & South Sandwich Islands flag": "🇬🇸",
    "Guatemala flag": "🇬🇹",
    "Guam flag": "🇬🇺",
    "Guinea Bissau flag": "🇬🇼",
    "Guyana flag": "🇬🇾",
    "Hong Kong SAR China flag": "🇭🇰",
    "Heard & McDonald Islands flag": "🇭🇲",
    "Honduras flag": "🇭🇳",
    "Croatia flag": "🇭🇷",
    "Haiti flag": "🇭🇹",
    "Hungary flag": "🇭🇺",
    "Canary Islands flag": "🇮🇨",
    "Indonesia flag": "🇮🇩",
    "Ireland flag": "🇮🇪",
    "Israel flag": "🇮🇱",
    "Isle of Man flag": "🇮🇲",
    "India flag": "🇮🇳",
    "British Indian Ocean Territory flag": "🇮🇴",
    "Iraq flag": "🇮🇶",
    "Iran flag": "🇮🇷",
    "Iceland flag": "🇮🇸",
    "Italy flag": "🇮🇹",
    "Jersey flag": "🇯🇪",
    "Jamaica flag": "🇯🇲",
    "Jordan flag": "🇯🇴",
    "Japan flag": "🇯🇵",
    "Kenya flag": "🇰🇪",
    "Kyrgyzstan flag": "🇰🇬",
    "Cambodia flag": "🇰🇭",
    "Kiribati flag": "🇰🇮",
    "Comoros flag": "🇰🇲",
    "St. Kitts & Nevis flag": "🇰🇳",
    "North Korea flag": "🇰🇵",
    "South Korea flag": "🇰🇷",
    "Kuwait flag": "🇰🇼",
    "Cayman Islands flag": "🇰🇾",
    "Kazakhstan flag": "🇰🇿",
    "Laos flag": "🇱🇦",
    "Lebanon flag": "🇱🇧",
    "St. Lucia flag": "🇱🇨",
    "Liechtenstein flag": "🇱🇮",
    "Sri Lanka flag": "🇱🇰",
    "Liberia flag": "🇱🇷",
    "Lesotho flag": "🇱🇸",
    "Lithuania flag": "🇱🇹",
    "Luxembourg flag": "🇱🇺",
    "Latvia flag": "🇱🇻",
    "Libya flag": "🇱🇾",
    "Morocco flag": "🇲🇦",
    "Monaco flag": "🇲🇨",
    "Moldova flag": "🇲🇩",
    "Montenegro flag": "🇲🇪",
    "St. Martin flag": "🇲🇫",
    "Madagascar flag": "🇲🇬",
    "Marshall Islands flag": "🇲🇭",
    "North Macedonia flag": "🇲🇰",
    "Mali flag": "🇲🇱",
    "Myanmar flag": "🇲🇲",
    "Mongolia flag": "🇲🇳",
    "Macao SAR China flag": "🇲🇴",
    "Northern Mariana Islands flag": "🇲🇵",
    "Martinique flag": "🇲🇶",
    "Mauritania flag": "🇲🇷",
    "Montserrat flag": "🇲🇸",
    "Malta flag": "🇲🇹",
    "Mauritius flag": "🇲🇺",
    "Maldives flag": "🇲🇻",
    "Malawi flag": "🇲🇼",
    "Mexico flag": "🇲🇽",
    "Malaysia flag": "🇲🇾",
    "Mozambique flag": "🇲🇿",
    "Namibia flag": "🇳🇦",
    "New Caledonia flag": "🇳🇨",
    "Niger Republic flag": "🇳🇪",
    "Nigeria flag": "🇳🇬",
    "Norfolk Island flag": "🇳🇫",
    "Nicaragua flag": "🇳🇮",
    "Netherlands flag": "🇳🇱",
    "Norway flag": "🇳🇴",
    "Nepal flag": "🇳🇵",
    "Nauru flag": "🇳🇷",
    "Niue flag": "🇳🇺",
    "New Zealand flag": "🇳🇿",
    "Oman flag": "🇴🇲",
    "Panama flag": "🇵🇦",
    "Peru flag": "🇵🇪",
    "French Polynesia flag": "🇵🇫",
    "Papua New Guinea flag": "🇵🇬",
    "Philippines flag": "🇵🇭",
    "Pakistan flag": "🇵🇰",
    "Poland flag": "🇵🇱",
    "St. Pierre & Miquelon flag": "🇵🇲",
    "itcairn Islands flag": "🇵🇳",
    "Puerto Rico flag": "🇵🇷",
    "Palestinian Territories flag": "🇵🇸",
    "Portugal flag": "🇵🇹",
    "Palau flag": "🇵🇼",
    "Paraguay flag": "🇵🇾",
    "Qatar flag": "🇶🇦",
    "Réunion flag": "🇷🇪",
    "Romania flag": "🇷🇴",
    "Serbia flag": "🇷🇸",
    "Russia flag": "🇷🇺",
    "Rwanda flag": "🇷🇼",
    "Saudi Arabia flag": "🇸🇦",
    "Solomon Islands flag": "🇸🇧",
    "Seychelles flag": "🇸🇨",
    "Sudan flag": "🇸🇩",
    "Sweden flag": "🇸🇪",
    "Singapore flag": "🇸🇬",
    "St. Helena flag": "🇸🇭",
    "Slovenia flag": "🇸🇮",
    "Svalbard & Jan Mayen flag": "🇸🇯",
    "Slovakia flag": "🇸🇰",
    "Sierra Leone flag": "🇸🇱",
    "San Marino flag": "🇸🇲",
    "Senegal flag": "🇸🇳",
    "Somalia flag": "🇸🇴",
    "Suriname flag": "🇸🇷",
    "South Sudan flag": "🇸🇸",
    "São Tomé & Príncipe flag": "🇸🇹",
    "El Salvador flag": "🇸🇻",
    "Saint Maarten flag": "🇸🇽",
    "Syria flag": "🇸🇾",
    "Eswatini flag": "🇸🇿",
    "Tristan da Cunha flag": "🇹🇦",
    "Turks & Caicos Islands flag": "🇹🇨",
    "Chad flag": "🇹🇩",
    "French Southern Territories flag": "🇹🇫",
    "Togo flag": "🇹🇬",
    "Thailand flag": "🇹🇭",
    "Tajikistan flag": "🇹🇯",
    "Tokelau flag": "🇹🇰",
    "Timor-Leste flag": "🇹🇱",
    "Turkmenistan flag": "🇹🇲",
    "Tunisia flag": "🇹🇳",
    "Tonga flag": "🇹🇴",
    "Turkey flag": "🇹🇷",
    "Trinidad & Tobago flag": "🇹🇹",
    "Tuvalu flag": "🇹🇻",
    "Taiwan flag": "🇹🇼",
    "Tanzania flag": "🇹🇿",
    "Ukraine flag": "🇺🇦",
    "Uganda flag": "🇺🇬",
    "U.S. Outlying Islands flag": "🇺🇲",
    "United Nations flag": "🇺🇳",
    "United States flag": "🇺🇸",
    "Uruguay flag": "🇺🇾",
    "Uzbekistan flag": "🇺🇿",
    "Vatican City flag": "🇻🇦",
    "St. Vincent & Grenadines flag": "🇻🇨",
    "Venezuela flag": "🇻🇪",
    "British Virgin Islands flag": "🇻🇬",
    "U.S. Virgin Islands flag": "🇻🇮",
    "Vietnam flag": "🇻🇳",
    "Vanuatu flag": "🇻🇺",
    "Wallis & Futuna flag": "🇼🇫",
    "Samoa flag": "🇼🇸",
    "Kosovo flag": "🇽🇰",
    "Yemen flag": "🇾🇪",
    "Mayotte flag": "🇾🇹",
    "South Africa flag": "🇿🇦",
    "Zambia flag": "🇿🇲",
    "Zimbabwe flag": "🇿🇼",
    "England flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Scotland flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Wales flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
}

def get_one_wechat_emoji() -> str:
    return choice(wechat_emoji)
    
def get_one_emoji() -> str:
    return choice(list(all_emoji.values()))